=== yoyolicoris/music-demixing-challenge-ismir-2021-entry/utils/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "instance": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "args": {
                    "type": "object"
                }
            },
            "required": [
                "type",
                "args"
            ]
        }
    },
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "arch": {
            "$ref": "#/definitions/instance"
        },
        "dataset": {
            "type": "object",
            "properties": {
                "train": {
                    "$ref": "#/definitions/instance"
                },
                "valid": {
                    "$ref": "#/definitions/instance"
                }
            },
            "required": [
                "train",
                "valid"
            ]
        },
        "optimizer": {
            "$ref": "#/definitions/instance"
        },
        "loss": {
            "$ref": "#/definitions/instance"
        },
        "lr_scheduler": {
            "$ref": "#/definitions/instance"
        },
        "data_loader": {
            "type": "object",
            "properties": {
                "train": {
                    "type": "object",
                    "properties": {
                        "batch_size": {
                            "type": "integer"
                        },
                        "shuffle": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "batch_size",
                        "shuffle"
                    ]
                },
                "valid": {
                    "type": "object",
                    "properties": {
                        "batch_size": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "batch_size"
                    ]
                }
            },
            "required": [
                "train",
                "valid"
            ]
        },
        "trainer": {
            "type": "object",
            "properties": {
                "epochs": {
                    "type": "integer"
                },
                "save_dir": {
                    "type": "string"
                },
                "log_dir": {
                    "type": "string"
                },
                "cum_steps": {
                    "type": "integer"
                },
                "patience": {
                    "type": "integer"
                },
                "amp_enabled": {
                    "type": "boolean"
                },
                "val_epoch_length": {
                    "type": "null"
                },
                "validate_every": {
                    "type": "integer"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "n_fft": {
                    "type": "integer"
                },
                "hop_length": {
                    "type": "integer"
                },
                "extra_monitor": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "time_domain": {
                    "type": "boolean"
                }
            },
            "required": [
                "epochs",
                "save_dir",
                "log_dir",
                "cum_steps",
                "patience",
                "amp_enabled",
                "val_epoch_length",
                "validate_every",
                "targets",
                "extra_monitor"
            ]
        }
    },
    "required": [
        "name",
        "arch",
        "dataset",
        "optimizer",
        "loss",
        "lr_scheduler",
        "data_loader",
        "trainer"
    ]
}

=== yoyolicoris/music-demixing-challenge-ismir-2021-entry/configs/demucs.json
{
    "name": "Demucs",
    "arch": {
        "type": "Demucs",
        "args": {
            "channels": 64
        }
    },
    "dataset": {
        "train": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "train",
                "split": null,
                "seq_duration": 10,
                "samples_per_track": 150,
                "random": true,
                "random_track_mix": true
            }
        },
        "valid": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "train",
                "split": "valid",
                "seq_duration": 10
            }
        }
    },
    "optimizer": {
        "type": "Adam",
        "args": {
            "lr": 3e-4
        }
    },
    "loss": {
        "type": "L1Loss",
        "args": {}
    },
    "lr_scheduler": {
        "type": "ReduceLROnPlateau",
        "args": {
            "factor": 0.3,
            "patience": 400,
            "verbose": true
        }
    },
    "data_loader": {
        "train": {
            "batch_size": 4,
            "shuffle": true,
            "drop_last": true,
            "num_workers": 2,
            "prefetch_factor": 6,
            "pin_memory": false
        },
        "valid": {
            "batch_size": 4,
            "num_workers": 2,
            "prefetch_factor": 6,
            "pin_memory": false
        }
    },
    "trainer": {
        "epochs": 360,
        "save_dir": "saved/",
        "log_dir": "runs/",
        "cum_steps": 16,
        "patience": 1000,
        "amp_enabled": true,
        "val_epoch_length": null,
        "validate_every": 1,
        "targets": [
            "bass",
            "drums",
            "vocals",
            "other"
        ],
        "extra_monitor": [],
        "time_domain": true
    }
}

=== yoyolicoris/music-demixing-challenge-ismir-2021-entry/configs/gmvae_denoise.json
{
    "name": "GMVAESupervised",
    "arch": {
        "type": "GMVAEDenoise",
        "args": {
            "n_fft": 4096,
            "hidden_channels": 512,
            "max_bins": 1487,
            "nb_layers": 3,
            "latent_size": 256,
            "c": 5
        }
    },
    "dataset": {
        "train": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "train",
                "split": "train",
                "seq_duration": 6.0,
                "samples_per_track": 64,
                "random": true,
                "random_track_mix": true
            }
        },
        "valid": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "train",
                "split": "valid",
                "seq_duration": 6.0
            }
        }
    },
    "optimizer": {
        "type": "Adam",
        "args": {
            "lr": 1e-3,
            "weight_decay": 1e-5
        }
    },
    "loss": {
        "type": "VAE_ELBO",
        "args": {
            "infer_class": true,
            "combine_sources": false
        }
    },
    "lr_scheduler": {
        "type": "ReduceLROnPlateau",
        "args": {
            "factor": 0.3,
            "patience": 80,
            "verbose": true
        }
    },
    "data_loader": {
        "train": {
            "batch_size": 12,
            "shuffle": true,
            "drop_last": true,
            "num_workers": 2,
            "prefetch_factor": 6,
            "pin_memory": false
        },
        "valid": {
            "batch_size": 4,
            "num_workers": 2,
            "prefetch_factor": 4,
            "pin_memory": false
        }
    },
    "trainer": {
        "epochs": 100,
        "save_dir": "saved/",
        "log_dir": "runs/",
        "cum_steps": 1,
        "patience": 1000,
        "amp_enabled": false,
        "val_epoch_length": null,
        "validate_every": 1,
        "targets": [
            "bass",
            "drums",
            "vocals",
            "other"
        ],
        "n_fft": 4096,
        "hop_length": 1024,
        "extra_monitor": [
            "elbo",
            "recon_ll",
            "z_kl",
            "mse",
            "class_ll"
        ],
        "encoder_phase": false
    }
}

=== yoyolicoris/music-demixing-challenge-ismir-2021-entry/unet.json
{
    "name": "UNet (Vocals)",
    "arch": {
        "type": "UNet",
        "args": {}
    },
    "dataset": {
        "train": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "train",
                "split": "train",
                "seq_duration": 12.0,
                "samples_per_track": 64,
                "random": true,
                "random_track_mix": true
            }
        },
        "valid": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "train",
                "split": "valid",
                "seq_duration": 12.0
            }
        }
    },
    "optimizer": {
        "type": "Adam",
        "args": {
            "lr": 1e-4
        }
    },
    "loss": {
        "type": "MDLoss",
        "args": {
            "mcoeff": 10,
            "n_fft": 4096,
            "hop_length": 1024
        }
    },
    "lr_scheduler": {
        "type": "ReduceLROnPlateau",
        "args": {
            "factor": 0.3,
            "patience": 40,
            "verbose": true
        }
    },
    "data_loader": {
        "train": {
            "batch_size": 4,
            "shuffle": true,
            "drop_last": true,
            "num_workers": 4,
            "pin_memory": true
        },
        "valid": {
            "batch_size": 4,
            "num_workers": 4,
            "pin_memory": true
        }
    },
    "trainer": {
        "epochs": 500,
        "save_dir": "saved/",
        "log_dir": "runs/",
        "cum_steps": 1,
        "patience": 1000,
        "amp_enabled": false,
        "val_epoch_length": null,
        "validate_every": 1,
        "targets": [
            "vocals"
        ],
        "n_fft": 4096,
        "hop_length": 1024,
        "extra_monitor": [
            "loss_f",
            "loss_t"
        ]
    }
}

=== yoyolicoris/music-demixing-challenge-ismir-2021-entry/configs/demucs_split.json
{
    "name": "DemucsSplit",
    "arch": {
        "type": "DemucsSplit",
        "args": {
            "channels": 48
        }
    },
    "dataset": {
        "train": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "train",
                "split": null,
                "seq_duration": 10,
                "samples_per_track": 120,
                "random": true,
                "random_track_mix": true
            }
        },
        "valid": {
            "type": "FastMUSDB",
            "args": {
                "root": "~/Datasets/musdb18hq/",
                "subsets": "test",
                "split": null,
                "seq_duration": 10
            }
        }
    },
    "optimizer": {
        "type": "Adam",
        "args": {
            "lr": 3e-4
        }
    },
    "loss": {
        "type": "CL1Loss",
        "args": {}
    },
    "lr_scheduler": {
        "type": "ReduceLROnPlateau",
        "args": {
            "factor": 0.3,
            "patience": 1800,
            "verbose": true
        }
    },
    "data_loader": {
        "train": {
            "batch_size": 3,
            "shuffle": true,
            "drop_last": true,
            "num_workers": 2,
            "prefetch_factor": 4,
            "pin_memory": true
        },
        "valid": {
            "batch_size": 4,
            "num_workers": 2,
            "prefetch_factor": 4,
            "pin_memory": true
        }
    },
    "trainer": {
        "epochs": 360,
        "save_dir": "saved/",
        "log_dir": "runs/",
        "cum_steps": 21,
        "patience": 360,
        "amp_enabled": true,
        "val_epoch_length": null,
        "validate_every": 5,
        "targets": [
            "bass",
            "drums",
            "vocals",
            "other"
        ],
        "extra_monitor": [],
        "time_domain": true
    }
}
